### ISSUE TITLE
Test for first comparison op should be enforced

### ISSUE THREAD

**Issue by edw** [AZHenley/teenytinycompiler#2]
https://github.com/AZHenley/teenytinycompiler/blob/34655ada2594b39a4d52d4615f45d4394eef4287/part2/parse.py#L172

There should be an `else` on the referenced `if` statement that aborts in the event that `self.isComparisonOperator()` evaluates to `False`.

**Comment by AZHenley** [comment]
Nice catch! Thank you.

**Comment by edw** [comment]
You’re welcome. And I want to thank you, because, inspired by your tutorials, I’m writing a Lisp compiler in C, hoping to eventually target 65C02 assembly, write a self-hosted version, and run it on my childhood Apple //c.
