### ISSUE TITLE
Any Updates on Part-3

### ISSUE THREAD

**Issue by djb4ai** [AZHenley/teenytinycompiler#3]
I was reading your post, waiting for part-3 of the series.

**Comment by hhold** [comment]
PLEASE WRITE PART THREE BEEN WAITING FOR WEEKS ALSO SORRY IF YOU'RE BUSY TAKE YOUR TIME BUT ALSO PLEASE WRITE IT THANK YOU

**Comment by AZHenley** [comment]
Released: http://web.eecs.utk.edu/~azh/blog/teenytinycompiler3.html

**Comment by djb4ai** [comment]
@AZHenley Thank you so much
